import type {
  TEXT_COLOR__ACCENT,
  TEXT_COLOR__BRAND,
  TEXT_COLOR__DANGER,
  TEXT_COLOR__DISABLED,
  TEXT_COLOR__INFO,
  TEXT_COLOR__INTERACTIVE,
  TEXT_COLOR__INTERACTIVE_HOVER,
  TEXT_COLOR__INVERSE,
  TEXT_COLOR__MUTED,
  TEXT_COLOR__PRIMARY,
  TEXT_COLOR__SECONDARY,
  TEXT_COLOR__SUCCESS,
  TEXT_COLOR__WARNING,
  TEXT_SIZE__LG,
  TEXT_SIZE__MD,
  TEXT_SIZE__SM,
  TEXT_SIZE__XL,
  TEXT_VARIANT__BODY,
  TEXT_VARIANT__CAPTION,
  TEXT_VARIANT__DISPLAY,
  TEXT_VARIANT__HEADING,
  TEXT_VARIANT__LABEL,
  TEXT_VARIANT__SUBHEADING,
  TEXT_WEIGHT__BOLD,
  TEXT_WEIGHT__LIGHT,
  TEXT_WEIGHT__MEDIUM,
} from './text.css.js';

type TextType =
  | typeof TEXT_VARIANT__DISPLAY
  | typeof TEXT_VARIANT__HEADING
  | typeof TEXT_VARIANT__SUBHEADING
  | typeof TEXT_VARIANT__BODY
  | typeof TEXT_VARIANT__CAPTION
  | typeof TEXT_VARIANT__LABEL;

type TextSize = typeof TEXT_SIZE__XL | typeof TEXT_SIZE__LG | typeof TEXT_SIZE__MD | typeof TEXT_SIZE__SM;

type TextWeight = typeof TEXT_WEIGHT__LIGHT | typeof TEXT_WEIGHT__MEDIUM | typeof TEXT_WEIGHT__BOLD;

type TextColor =
  | typeof TEXT_COLOR__PRIMARY
  | typeof TEXT_COLOR__SECONDARY
  | typeof TEXT_COLOR__MUTED
  | typeof TEXT_COLOR__DISABLED
  | typeof TEXT_COLOR__INVERSE
  | typeof TEXT_COLOR__INTERACTIVE
  | typeof TEXT_COLOR__INTERACTIVE_HOVER
  | typeof TEXT_COLOR__SUCCESS
  | typeof TEXT_COLOR__WARNING
  | typeof TEXT_COLOR__DANGER
  | typeof TEXT_COLOR__INFO
  | typeof TEXT_COLOR__BRAND
  | typeof TEXT_COLOR__ACCENT;

export type { TextType, TextSize, TextWeight, TextColor };
