import { createTheme } from '@vanilla-extract/css';

import { themeContract } from '../tokens/tokens.css.js';
import { COLORS__NEUTRAL } from '../tokens/primitives/colors.js';
import { SPACING } from '../tokens/primitives/spacing.js';
import { FONT_SIZE, FONT_WEIGHT, LINE_HEIGHT, LETTER_SPACING } from '../tokens/primitives/typography.js';
import { BORDER_RADIUS, BORDER_WIDTH } from '../tokens/primitives/borders.js';
import { BOX_SHADOW } from '../tokens/primitives/shadows.js';

const lightTheme = createTheme(themeContract, {
  colors: {
    'action.primary': `oklch(${COLORS__NEUTRAL[50]})`,
    'action.primary.hover': `oklch(${COLORS__NEUTRAL[50]})`,
    'action.primary.active': `oklch(${COLORS__NEUTRAL[50]})`,
    'action.primary.disabled': `oklch(${COLORS__NEUTRAL[50]})`,
    'action.secondary': `oklch(${COLORS__NEUTRAL[50]})`,
    'action.secondary.hover': `oklch(${COLORS__NEUTRAL[50]})`,
    'action.secondary.active': `oklch(${COLORS__NEUTRAL[50]})`,
    'action.secondary.disabled': `oklch(${COLORS__NEUTRAL[50]})`,
    'action.destructive': `oklch(${COLORS__NEUTRAL[50]})`,
    'action.destructive.hover': `oklch(${COLORS__NEUTRAL[50]})`,
    'action.destructive.active': `oklch(${COLORS__NEUTRAL[50]})`,
    'action.destructive.disabled': `oklch(${COLORS__NEUTRAL[50]})`,
    'action.ghost': `oklch(${COLORS__NEUTRAL[50]})`,
    'action.ghost.hover': `oklch(${COLORS__NEUTRAL[50]})`,
    'action.ghost.active': `oklch(${COLORS__NEUTRAL[50]})`,
    'action.ghost.disabled': `oklch(${COLORS__NEUTRAL[50]})`,
    'border.default': `oklch(${COLORS__NEUTRAL[50]})`,
    'border.subtle': `oklch(${COLORS__NEUTRAL[50]})`,
    'border.strong': `oklch(${COLORS__NEUTRAL[50]})`,
    'border.interactive': `oklch(${COLORS__NEUTRAL[50]})`,
    'border.interactive.hover': `oklch(${COLORS__NEUTRAL[50]})`,
    'border.interactive.active': `oklch(${COLORS__NEUTRAL[50]})`,
    'border.focus': `oklch(${COLORS__NEUTRAL[50]})`,
    'border.success': `oklch(${COLORS__NEUTRAL[50]})`,
    'border.warning': `oklch(${COLORS__NEUTRAL[50]})`,
    'border.error': `oklch(${COLORS__NEUTRAL[50]})`,
    'border.info': `oklch(${COLORS__NEUTRAL[50]})`,
    'border.action.primary': `oklch(${COLORS__NEUTRAL[50]})`,
    'border.action.secondary': `oklch(${COLORS__NEUTRAL[50]})`,
    'border.action.destructive': `oklch(${COLORS__NEUTRAL[50]})`,
    'border.action.disabled': `oklch(${COLORS__NEUTRAL[50]})`,
    'text.primary': `oklch(${COLORS__NEUTRAL[50]})`,
    'text.secondary': `oklch(${COLORS__NEUTRAL[50]})`,
    'text.tertiary': `oklch(${COLORS__NEUTRAL[50]})`,
    'text.interactive': `oklch(${COLORS__NEUTRAL[50]})`,
    'text.interactive.hover': `oklch(${COLORS__NEUTRAL[50]})`,
    'text.interactive.active': `oklch(${COLORS__NEUTRAL[50]})`,
    'text.success': `oklch(${COLORS__NEUTRAL[50]})`,
    'text.warning': `oklch(${COLORS__NEUTRAL[50]})`,
    'text.error': `oklch(${COLORS__NEUTRAL[50]})`,
    'text.info': `oklch(${COLORS__NEUTRAL[50]})`,
    'text.inverse': `oklch(${COLORS__NEUTRAL[50]})`,
    'text.disabled': `oklch(${COLORS__NEUTRAL[50]})`,
    'surface.bg.primary': `oklch(${COLORS__NEUTRAL[50]})`,
    'surface.bg.secondary': `oklch(${COLORS__NEUTRAL[50]})`,
    'surface.bg.tertiary': `oklch(${COLORS__NEUTRAL[50]})`,
    'surface.bg.interactive': `oklch(${COLORS__NEUTRAL[50]})`,
    'surface.bg.interactive.hover': `oklch(${COLORS__NEUTRAL[50]})`,
    'surface.bg.interactive.active': `oklch(${COLORS__NEUTRAL[50]})`,
    'surface.bg.success': `oklch(${COLORS__NEUTRAL[50]})`,
    'surface.bg.warning': `oklch(${COLORS__NEUTRAL[50]})`,
    'surface.bg.error': `oklch(${COLORS__NEUTRAL[50]})`,
    'surface.bg.info': `oklch(${COLORS__NEUTRAL[50]})`,
    'surface.bg.overlay': `oklch(${COLORS__NEUTRAL[50]})`,
    'surface.bg.disabled': `oklch(${COLORS__NEUTRAL[50]})`,
    'surface.bg.inverse': `oklch(${COLORS__NEUTRAL[50]})`,
    'icon.primary': `oklch(${COLORS__NEUTRAL[50]})`,
    'icon.secondary': `oklch(${COLORS__NEUTRAL[50]})`,
    'icon.tertiary': `oklch(${COLORS__NEUTRAL[50]})`,
    'icon.interactive': `oklch(${COLORS__NEUTRAL[50]})`,
    'icon.interactive.hover': `oklch(${COLORS__NEUTRAL[50]})`,
    'icon.interactive.active': `oklch(${COLORS__NEUTRAL[50]})`,
    'icon.success': `oklch(${COLORS__NEUTRAL[50]})`,
    'icon.warning': `oklch(${COLORS__NEUTRAL[50]})`,
    'icon.error': `oklch(${COLORS__NEUTRAL[50]})`,
    'icon.info': `oklch(${COLORS__NEUTRAL[50]})`,
    'icon.inverse': `oklch(${COLORS__NEUTRAL[50]})`,
    'icon.disabled': `oklch(${COLORS__NEUTRAL[50]})`,
    'input.bg.default': `oklch(${COLORS__NEUTRAL[50]})`,
    'input.bg.hover': `oklch(${COLORS__NEUTRAL[50]})`,
    'input.bg.focus': `oklch(${COLORS__NEUTRAL[50]})`,
    'input.bg.disabled': `oklch(${COLORS__NEUTRAL[50]})`,
    'input.bg.error': `oklch(${COLORS__NEUTRAL[50]})`,
    'input.border.default': `oklch(${COLORS__NEUTRAL[50]})`,
    'input.border.hover': `oklch(${COLORS__NEUTRAL[50]})`,
    'input.border.focus': `oklch(${COLORS__NEUTRAL[50]})`,
    'input.border.error': `oklch(${COLORS__NEUTRAL[50]})`,
    'input.border.disabled': `oklch(${COLORS__NEUTRAL[50]})`,
    'input.text.default': `oklch(${COLORS__NEUTRAL[50]})`,
    'input.text.placeholder': `oklch(${COLORS__NEUTRAL[50]})`,
    'input.text.disabled': `oklch(${COLORS__NEUTRAL[50]})`,
    'shadow.default': `oklch(${COLORS__NEUTRAL[50]})`,
    'shadow.subtle': `oklch(${COLORS__NEUTRAL[50]})`,
    'shadow.strong': `oklch(${COLORS__NEUTRAL[50]})`,
    'shadow.interactive': `oklch(${COLORS__NEUTRAL[50]})`,
    'shadow.focus': `oklch(${COLORS__NEUTRAL[50]})`,
    'shadow.success': `oklch(${COLORS__NEUTRAL[50]})`,
    'shadow.warning': `oklch(${COLORS__NEUTRAL[50]})`,
    'shadow.error': `oklch(${COLORS__NEUTRAL[50]})`,
  },
  spacing: {
    0: SPACING[0],
    px: SPACING.px,
    0.5: SPACING[0.5],
    1: SPACING[1],
    1.5: SPACING[1.5],
    2: SPACING[2],
    2.5: SPACING[2.5],
    3: SPACING[3],
    3.5: SPACING[3.5],
    4: SPACING[4],
    5: SPACING[5],
    6: SPACING[6],
    7: SPACING[7],
    8: SPACING[8],
    9: SPACING[9],
    10: SPACING[10],
    11: SPACING[11],
    12: SPACING[12],
    14: SPACING[14],
    16: SPACING[16],
    20: SPACING[20],
    24: SPACING[24],
    28: SPACING[28],
    32: SPACING[32],
    36: SPACING[36],
    40: SPACING[40],
    44: SPACING[44],
    48: SPACING[48],
    52: SPACING[52],
    56: SPACING[56],
    60: SPACING[60],
    64: SPACING[64],
    72: SPACING[72],
    80: SPACING[80],
    96: SPACING[96],
  },
  fontSize: {
    xs: FONT_SIZE.xs,
    sm: FONT_SIZE.sm,
    base: FONT_SIZE.base,
    lg: FONT_SIZE.lg,
    xl: FONT_SIZE.xl,
    '2xl': FONT_SIZE['2xl'],
    '3xl': FONT_SIZE['3xl'],
    '4xl': FONT_SIZE['4xl'],
    '5xl': FONT_SIZE['5xl'],
    '6xl': FONT_SIZE['6xl'],
    '7xl': FONT_SIZE['7xl'],
    '8xl': FONT_SIZE['8xl'],
    '9xl': FONT_SIZE['9xl'],
  },
  fontWeight: {
    thin: FONT_WEIGHT.thin,
    extralight: FONT_WEIGHT.extralight,
    light: FONT_WEIGHT.light,
    normal: FONT_WEIGHT.normal,
    medium: FONT_WEIGHT.medium,
    semibold: FONT_WEIGHT.semibold,
    bold: FONT_WEIGHT.bold,
    extrabold: FONT_WEIGHT.extrabold,
    black: FONT_WEIGHT.black,
  },
  lineHeight: {
    none: LINE_HEIGHT.none,
    tight: LINE_HEIGHT.tight,
    snug: LINE_HEIGHT.snug,
    normal: LINE_HEIGHT.normal,
    relaxed: LINE_HEIGHT.relaxed,
    loose: LINE_HEIGHT.loose,
    3: LINE_HEIGHT[3],
    4: LINE_HEIGHT[4],
    5: LINE_HEIGHT[5],
    6: LINE_HEIGHT[6],
    7: LINE_HEIGHT[7],
    8: LINE_HEIGHT[8],
    9: LINE_HEIGHT[9],
    10: LINE_HEIGHT[10],
  },
  letterSpacing: {
    tighter: LETTER_SPACING.tighter,
    tight: LETTER_SPACING.tight,
    normal: LETTER_SPACING.normal,
    wide: LETTER_SPACING.wide,
    wider: LETTER_SPACING.wider,
    widest: LETTER_SPACING.widest,
  },
  borderRadius: {
    none: BORDER_RADIUS.none,
    sm: BORDER_RADIUS.sm,
    base: BORDER_RADIUS.base,
    md: BORDER_RADIUS.md,
    lg: BORDER_RADIUS.lg,
    xl: BORDER_RADIUS.xl,
    '2xl': BORDER_RADIUS['2xl'],
    '3xl': BORDER_RADIUS['3xl'],
    full: BORDER_RADIUS.full,
  },
  borderWidth: {
    0: BORDER_WIDTH[0],
    1: BORDER_WIDTH[1],
    2: BORDER_WIDTH[2],
    4: BORDER_WIDTH[4],
    8: BORDER_WIDTH[8],
  },
  boxShadow: {
    none: BOX_SHADOW.none,
    sm: BOX_SHADOW.sm,
    base: BOX_SHADOW.base,
    md: BOX_SHADOW.md,
    lg: BOX_SHADOW.lg,
    xl: BOX_SHADOW.xl,
    '2xl': BOX_SHADOW['2xl'],
    inner: BOX_SHADOW.inner,
  },
});

export { lightTheme };
