import type {
  BUTTON_SIZE__LARGE,
  BUTTON_SIZE__MEDIUM,
  BUTTON_SIZE__SMALL,
  BUTTON_VARIANT__DESTRUCTIVE,
  BUTTON_VARIANT__GHOST,
  BUTTON_VARIANT__LINK,
  BUTTON_VARIANT__OUTLINE,
  BUTTON_VARIANT__PRIMARY,
  BUTTON_VARIANT__SECONDARY,
} from './button.css.js';

type ButtonVariant =
  | typeof BUTTON_VARIANT__PRIMARY
  | typeof BUTTON_VARIANT__SECONDARY
  | typeof BUTTON_VARIANT__OUTLINE
  | typeof BUTTON_VARIANT__DESTRUCTIVE
  | typeof BUTTON_VARIANT__GHOST
  | typeof BUTTON_VARIANT__LINK;

type ButtonSize = typeof BUTTON_SIZE__LARGE | typeof BUTTON_SIZE__MEDIUM | typeof BUTTON_SIZE__SMALL;

export type { ButtonVariant, ButtonSize };
